feat(BUX-594): migrate bux-wallet-backend name
bitcoin-sv/spv-wallet-web-backend pull request #58
Opened 2024-02-14 10:04 UTC by chris-4chain

# Pull Request Checklist

- [ ] 📖 I created my PR using provided  : [CODE_STANDARDS](https://github.com/bitcoin-sv/bux-wallet-backend/blob/main/.github/CODE_STANDARDS.md)
- [ ] 📖 I have read the short Code of Conduct: [CODE_OF_CONDUCT](https://github.com/bitcoin-sv/bux-wallet-backend/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] 🏠 I tested my changes locally.
- [ ] ✅ I have provided tests for my changes.
- [ ] 📝 I have used conventional commits.
- [ ] 📗 I have updated any related documentation.
- [ ] 💾 PR was issued based on the Github or Jira issue.

2024-02-15 07:35 UTC, kuba-4chain reviewed
There's still buxmodels to rename, right? Or should it be renamed in this PR?

2024-02-15 07:35 UTC, kuba-4chain commented on .github/CODE_STANDARDS.md
>  ```bash
We removed `bash` from here in spv-wallet-web-frontend, so we can do it here as well :)

2024-02-15 07:45 UTC, dorzepowski requested changes

2024-02-15 07:45 UTC, dorzepowski commented on go.mod
> +module web-backend
I agree, I would go with a {org}/{repo} name as in other repositories, to make it consistent and easier to find.

2024-02-15 07:46 UTC, chris-4chain commented on domain/users/interfaces.go
> +		CreateAndFinalizeTransaction(recipients []*transports.Recipients, metadata *models.Metadata) (DraftTransaction, error)
I suppose you commented wrong line, because I can't figure out what do you mean in the context of the selected code.

2024-02-15 07:51 UTC, chris-4chain commented on go.mod
> +module web-backend
Being consistent with other repos convinced me - I'll do as you wish 👍

2024-02-15 07:56 UTC, kuba-4chain commented on domain/users/interfaces.go
> +		CreateAndFinalizeTransaction(recipients []*transports.Recipients, metadata *models.Metadata) (DraftTransaction, error)
Sorry for not being specific, there's `metadata *models.Metadata` argument here. I was suggesting a change from `models` to `spv-wallet-models` or something more specific

2024-02-15 08:37 UTC, chris-4chain commented on domain/transactions/transactions_service.go
> +	clientFactory users.ClientFactory
As we agreed on the meeting - I'll stay with `adminClient` & `userClient`.

2024-02-15 08:54 UTC, chris-4chain commented on domain/users/interfaces.go
> +		CreateAndFinalizeTransaction(recipients []*transports.Recipients, metadata *models.Metadata) (DraftTransaction, error)
Agreed - but until the models package is renamed, I can't proceed without using named imports. For now, I could revert the changes where I've added named imports and leave them as they were. Once go-buxmodels and go-buxclient are renamed, the person responsible for this should also update their names in this repository.

2024-02-15 09:00 UTC, chris-4chain commented on README.md
> +---
I'm 99% sure that even if I reverse it now, some next ctrl+s action will re-format this to the three-dahsed form and I'll overlook this. 

So, I'd like to ask for clear policy - disable formatter for `md`, establish our rules or let my valid change to stay.

2024-02-15 09:54 UTC, chris-4chain commented on go.mod
> +module web-backend
Done 👍

2024-02-15 10:01 UTC, chris-4chain commented
> There's still buxmodels to rename, right? Or should it be renamed in this PR?

@kuba-4chain Generally, in the description I've put `What's left to do` and it should be done by a person who makes changes in mentioned packages/dependencies. But - as I recall our discussion about that - it should be done in another PR(s).

For example - the person responsible for renaming the `go-buxclient` should also change the go.mod, imports and used-in-code module names.

2024-02-15 12:21 UTC, chris-4chain commented on domain/users/interfaces.go
> +		CreateAndFinalizeTransaction(recipients []*transports.Recipients, metadata *models.Metadata) (DraftTransaction, error)
Changed to `walletmodels`

2024-02-15 12:21 UTC, chris-4chain commented on domain/transactions/transactions_service.go
> +	userClient, err := s.clientFactory.CreateWithXpriv(xpriv)
Changed to `userWalletClient`

2024-02-15 12:26 UTC, chris-4chain commented on domain/transactions/transactions_service.go
> +	clientFactory users.ClientFactory
Generally I've changed all those names to:
- `adminWalletClient` 
- `userWalletClient`
- `walletClientFactory`

It's longer but *maybe* better to point out that all the clients are clients of our `spv-wallet`

2024-02-15 13:30 UTC, chris-4chain commented on transports/client/admin_client.go
> +package client
I thought we discussed the root package name only - but yea, it makes sense to rename the generic "client" name to `spvwallet`.

2024-02-15 13:33 UTC, dorzepowski commented on README.md
> +---
as I wrote, it's minor, so we can leave it as is, 
although it is sad, that your formatter is cutting a line as visually it is more "eye catching" if it is longer 😞

2024-02-15 13:35 UTC, chris-4chain commented on docs/http/status.http
I'll remove this

2024-02-15 13:44 UTC, chris-4chain commented on transports/client/admin_client.go
> +package client
Done 👍

2024-02-15 13:44 UTC, chris-4chain commented on docs/http/status.http
Removed

2024-02-15 15:28 UTC, kuba-4chain submitted a review, later dismissed

2024-02-16 06:54 UTC, kuba-4chain approved these changes

2024-02-16 07:54 UTC, dorzepowski approved these changes

2024-02-16 08:08 UTC, dorzepowski commented
testing

2024-02-16 09:52 UTC, merged